runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  COMMAND_PREFIX: "!"
  STAGING_GUILD: "336585541380341770"
  DISCORD_TOKEN: "Mzg3NDEwMzYzMzExOTgwNTQ0.XLvFSw.439z6EnHS2qQ_FWPy0crnPdhgyw"