import { Command } from '../lib/command';
import { getRandom, getRandomNumberBetween } from '../lib/utils';
import madlibs from 'mad-libber';

export class LootCommand extends Command {
	command = 'loot';
  
  data = [
    {
      id: 'Generic',
      prefix: [
        'Gore',
        'Maim',
        'Crush',
        'Thunder',
        'Light',
        'Void',
        'Shadow',
        'Fel',
        'Mist',
        'Doom',
        'Dark',
        'Plague',
        'Scourge',
        'Frost',
        'Ice',
        'Ash',
        'Blood',
        'Rot',
        'Flame',
        'Dragon',
        'Death',
        'Titan'
      ],
      suffix: [
        'howl',
        'flayer',
        'slayer',
        'gore',
        'cleaver',
        'smasher',
        'pummeler',
        'crusher',
        'scorn',
        'blood',
        'vein',
        'blossom',
        'bloom',
        'bane',
        'foe',
        'mourne',
        'bringer',
        'rot',
        'flame',
        'heart',
        'core',
        'breaker',
        'whisper',
        'spike',
        'reaper'
      ],
      type: [
        'axe',
        'blade',
        'maul',
        'warmaul',
        'sword',
        'greatsword',
        'greatblade',
        'greataxe',
        'warmaul',
        'warsword',
        'hammer',
        'warhammer',
        'spear',
        'club',
        'mace',
        'polearm',
        'halberd'
      ],
      source: [
        'fate',
        'the ravager',
        'the dark lord',
        'the forgotten king',
        'the nameless king',
        'the faceless one',
        'entwined destinies',
        'endless hunger',
        'endless war',
        'eternal struggle',
        'the apocalypse',
        'dark visions',
        'apocryphal fears',
        'the nightmare',
        'unending nightmares',
        'destiny'
      ]
    },
    {
      id: 'Orcish',
      prefix: [
        'Lok\'',
        'Akar\'',
        'Lohn\'',
        'Gol\'',
        'Throm-',
        'Karg',
        'Krag\'',
        'Mag\'',
        'Mok\'',
        'Nok\'',
        'Grom\'',
        'Naz',
        'Osh',
        'Gol\'',
        'Kor\'',
        'Om\'',
        'Zeth\'',
        'Zor',
        'Krom\''
      ],
      suffix: [
        'har',
        'narosh',
        'ganesh',
        'ganosh',
        'gosh',
        'goron',
        'nathal',
        'thaz',
        'krom',
        'kagh',
        'shar',
        'dashar',
        'mkral',
        'ra',
        'rogh',
        'gar',
        'gaz',
        'gor',
        'mok'
      ],
      type: [
        'axe',
        'blade',
        'maul',
        'warmaul',
        'sword',
        'greatsword',
        'greatblade',
        'greataxe',
        'warmaul',
        'warsword',
        'hammer',
        'warhammer',
        'spear',
        'club',
        'mace',
        'polearm',
        'poleaxe',
        'bloodhammer',
        'bloodsword',
        'bloodmace',
        'bloodmaul'
      ],
      source: [
        'the chieftan',
        'chieftans',
        'the warchief',
        'the warchiefs',
        'the elders',
        'the ancestors',
        'dark destinies',
        'entwined fate',
        'shattered worlds',
        'dying worlds',
        'dark bargains',
        'the hunt',
        'warring clans',
        'clan chieftans',
        'the clans',
        'the shattered hand',
        'the frostwolves',
        'the wolves',
        'bloody battles',
        'the great unifier',
        'honor',
        'forsaken honor',
        'eternal glory',
        'eternal combat',
        'dark power',
        'the blood rite',
        'the elements',
        'shamanistic rites',
        'ancestral spirits',
        'tribal unities',
        'unity',
        'fel rituals',
        'strength'
      ]
    },
    {
      id: 'Titan',
      prefix: [
        'Taesch',
        'Grond',
        'Aman\'',
        'Eon',
        'Aeth',
        'Norg',
        'Aggr',
        'Khaz',
        'Golg',
        'Chaer',
        'Gorr',
        'Khor',
        'Brael\'',
        'Uld'
      ],
      suffix: [
        'alach',
        'ar\'an',
        'al\'an',
        'anor',
        'eon',
        'immor',
        'anand',
        'aemar',
        'aman',
        'amal',
        'ibal',
        'us',
        'ar',
        'innar',
        'ir'
      ],
      type: [
        'greatstaff',
        'staff',
        'hammer',
        'greathammer',
        'blade',
        'greatblade',
        'sword',
        'greatsword',
        'bow',
        'greatbow',
        'reflecting prism',
        'scythe',
        'greatscythe',
        'crescent'
      ],
      source: [
        'the waning moon',
        'constellations',
        'constellar constructs',
        'planetary re-origination',
        'the cosmos',
        'the pantheon',
        'titanic wrath',
        'world shaping',
        'the world breaker',
        'the world shaper',
        'arcane reconstitution',
        'the world soul',
        'noble souls',
        'the watchers',
        'the twisting nether',
        'infinite possibilities',
        'the colossal order',
        'universal order',
        'the precursors',
        'infinite time',
        'life binding',
        'justice',
        'titanic ruin',
        'stars',
        'infinite possibilities',
        'unending torment'
      ]
    },
    {
      id: 'Elven',
      prefix: [
        'Aiel\'',
        'Thas\'',
        'Anu\'',
        'Ish\'',
        'Tel\'',
        'Shan\'',
        'Shal\'',
        'Kel\'',
        'Ren\'',
        'Quel\'',
        'Shel\'',
        'Quen\''
      ],
      suffix: [
        'doriyah',
        'dorah',
        'thoribas',
        'alah',
        'aranas',
        'danar',
        'thalanar',
        'shalan',
        'falan',
        'quenaar',
        'ibaan',
        'amaya',
        'quaya',
        'dan\'el'
      ],
      type: [
        'bow',
        'greatbow',
        'longbow',
        'shortbow',
        'staff',
        'quarterstaff',
        'greatstaff',
        'kukri',
        'dagger',
        'daggers',
        'knife',
        'sword',
        'dualswords',
        'quiver',
        'kunai',
        'crescent',
        'glaive',
        'warglaive'
      ],
      source: [
        'Quel\'danas',
        'Quel\'thalas',
        'the Sin\'dorei',
        'the Kal\'dorei',
        'the Ren\'dorei',
        'eternal night',
        'the archdruid',
        'the waning moon',
        'the full moon',
        'the world tree',
        'the moon',
        'the sunwell',
        'the sun',
        'Suramar',
        'Zin-Azshari',
        'Thalassian kings',
        'eternal ancestry',
        'Elune',
        'Elune\'s chosen',
        'the night warrior',
        'endless glades',
        'the whispering winds',
        'the forest song',
        'the wisps',
        'the ancients',
        'arcane constructs',
        'unending war',
        'endless withering',
        'rustling leaves',
        'the deep roots',
        'the deep forests'
      ]
    },
    {
      id: "Scourge",
      prefix: [
        'Bile',
        'Plague',
        'Rime',
        'Frost',
        'Ice',
        'Rot',
        'Vile',
        'Soul',
        'Blood',
        'Scourge',
        'Flesh',
        'Bone',
        'Death',
        'Gore',
        'Fester',
        'Wrath',
        'Lich',
        'Rune',
        'Ebon',
        'Shadow'
      ],
      suffix: [
        'mourne',
        'howl',
        'howler',
        'maw',
        'spike',
        'crush',
        'rot',
        'bringer',
        'reaper',
        'drinker',
        'feaster',
        'caller',
        'splinter',
        'foe',
        'blister',
        'flayer',
        'bound destroyer'
      ],
      type: [
        'sword',
        'greatsword',
        'runesword',
        'dreadblade',
        'runeblade',
        'greatblade',
        'greatmace',
        'corrupted blade',
        'maul',
        'dualswords',
        'morningstar',
        'axe',
        'greataxe',
        'dreadaxe',
        'runeaxe',
        'darkblade',
        'phylactery'
      ],
      source: [
        'the frozen wastes',
        'the blighted lands',
        'the borean tundra',
        'brutality',
        'cruelty',
        'undeath',
        'a thousand souls',
        'eternal torment',
        'unending suffering',
        'blighted agony',
        'the blood champion',
        'the fallen crusader',
        'runic corruption',
        'rising death',
        'the ashen wake',
        'ashes',
        'the ebon hold',
        'the dark crusade',
        'the ashen verdict',
        'unholy blight',
        'howling winds',
        'eternal damnation',
        'endless hunger'
      ]
    },
    {
      id: 'Divine',
      prefix: [
        'Light',
        'Morning',
        'Dawn',
        'Glory',
        'Flame',
        'Naaru',
        'Prophet',
        'L\'ura',
        'Xe\'ra',
        'A\'dal',
        'Angel',
        'Uther',
        'Tirion',
        'Turalyon',
        'Lothraxion',
        'Yrel',
        'Maraad',
        'Arator',
        'Anduin'
      ],
      suffix: [
        '\'s brilliance',
        '\'s decree',
        '\'s justice',
        '\'s might',
        '\'s hope',
        '\'s protection',
        '\'s zeal',
        '\'s truth',
        '\'s wisdom',
        '\'s vigor',
        '\'s spirit',
        '\'s vigil',
        '\'s devotion',
        '\'s divinity',
        '\'s divine law',
        '\'s wake',
        '\'s inspiration',
        '\'s reverence',
        '\'s wonder',
        '\'s faith',
        '\'s piety'
      ],
      type: [
        'hammer',
        'maul',
        'warhammer',
        'blessed hammer',
        'mace',
        'morningstar',
        'sword',
        'greatsword',
        'blessed sword',
        'blessed blade',
        'blade',
        'gavel',
        'libram'
      ],
      source: [
        'the Genedar',
        'the Xenedar',
        'the light',
        'the crusade',
        'the endless crusade',
        'eternal penance',
        'peace',
        'righteousness',
        'lasting peace',
        'the protector',
        'the silver hand',
        'the ashen verdict',
        'ashes',
        'rebirth',
        'the Naaru',
        'the highlord',
        'the high kings'
      ]
    },
    {
      id: 'Dwarven',
      prefix: [
        'Krum',
        'Gol ',
        'Dun ',
        'Gar ',
        'Gorm',
        'Kazad ',
        'Khâz-',
        'Daz-',
        'Knar-',
        'Lhor-',
        'Uldaz ',
        'Khûum ',
        'Khor ',
        'Dim ',
        'Bael ',
        'Draig ',
        'Khad',
        'Gwyr',
        'Than',
        'Thel ',
        'Thor ',
        'Dru'
      ],
      suffix: [
        'goldar',
        'arâm',
        'arûm',
        'amar',
        'baldar',
        'kadûm',
        'balor',
        'baldur',
        'gar',
        'modan',
        'magnar',
        'din',
        'algaz',
        'barok',
        'morogh',
        'ranos',
        'gen',
        'ganar',
        'goth',
        'gahn',
        'dan'
      ],
      material: [
        'Iron',
        'Stone',
        'Gem',
        'Diamond',
        'Mithril',
        'Boulder',
        'Silver',
        'Gold',
        'Ruby',
        'Shard',
        'Ore',
        'Steel',
        'Magma',
        'Lava',
        'Blood'
      ],
      descriptor: [
        'foe',
        'fell',
        'forger',
        'bender',
        'breaker',
        'crusher',
        'shaper',
        'killer',
        'slayer',
        'defender',
        'kiln',
        'finder',
        'binder'
      ],
      type: [
        'hammer',
        'greathammer',
        'warhammer',
        'battlehammer',
        'bloodhammer',
        'maul',
        'warmaul',
        'bloodmaul',
        'axe',
        'greataxe',
        'spiked axe',
        'battleaxe',
        'forgehammer',
        'sword',
        'greatsword',
        'blade',
        'greatblade'
      ],
      source: [
        'kings',
        'the blacksmiths',
        'the ironshapers',
        'the stonekin',
        'the earthen',
        'earthen heritage',
        'the royal bloodline',
        'the bronzebeards',
        'the wildhammers',
        'Emperor Thaurissan',
        'the firelord',
        'the flamekin',
        'endless battles',
        'warring clans',
        'the three clans',
        'the three crowns',
        'endless fortune',
        'dwarven fortitude',
        'dwarven strength',
        'the trogg wars',
        'the high thane',
        'Modimus Anvilmar',
        'the black anvil',
        'unstoppable magma',
        'the diamond king',
        'endless caverns',
        'the echoing halls'
      ]
    },
    {
      id: 'Troll',
      prefix: [
        'Taz\'',
        'Tek\'',
        'Zek\'',
        'Tal\'',
        'Tal',
        'Zand',
        'Taj',
        'Bwon\'',
        'Zul\'',
        'Sen\'',
        'Zun',
        'Rek',
        'Ty\'',
        'Tor\'',
        'Zeb',
        'Vol\'',
        'Hai\'',
        'Kai\'',
        'Hak'
      ],
      suffix: [
        'hazi',
        'kazi',
        'azi',
        'han',
        'azal',
        'atar',
        'tulak',
        'atul',
        'aman',
        'ai',
        'shi',
        'jin',
        'kaza',
        'kala',
        'zanga',
        'jamba',
        'arek',
        'rokh',
        'kar',
        'watha',
        'tual'
      ],
      type: [
        'spear',
        'axe',
        'sword',
        'knife',
        'blade',
        'ritual knife',
        'dagger',
        'glaive',
        'fang',
        'tusk',
        'javelin',
        'waraxe',
        'warsword',
        'handaxe',
        'warglaive'
      ],
      source: [
        'the echo isles',
        'executions',
        'the troll wars',
        'the shadow hunters',
        'Zandalar',
        'Zul\'jin',
        'the darkspear',
        'the Amani',
        'the Drakkari',
        'Gundrak',
        'Zul\'gurub',
        'the unified tribes',
        'the tribes',
        'the hexpriests',
        'the voodoo priests',
        'the soulflayer',
        'the Loa',
        'Rezan',
        'Bwonsamdi',
        'Zuldazar',
        'the Farraki empire',
        'the Gurubashi',
        'the golden temple',
        'the forest trolls',
        'the jungle trolls',
        'the ice trolls',
        'Vol\'jin'
      ]
    }, {
      id: 'Void',
      prefix: [
        'Shadow ',
        'Abyssal ',
        'Void ',
        'Shath\'yar ',
        'Aqir ',
        'Nraqi ',
        'Nerubian ',
        'Silithid ',
        'Corrupting ',
        'Beholder\'s ',
        'Corruptor\'s ',
        'The black'
      ],
      suffix: [
        'star',
        'compass',
        'whisper',
        'tentacle',
        'needle',
        'spike',
        'embrace',
        'wing',
        'tide',
        'eye',
        'claw',
        'tendril',
        'horror',
        'terror'
      ],
      type: [
        'dagger',
        'knife',
        'ritual knife',
        'blade',
        'sword',
        'divining rod',
        'eldritch artifact',
        'crystalline focus',
        'crystal ball'
      ],
      source: [
        'Ny\'alotha',
        'N\'zoth',
        'Yogg-saron',
        'Y\'shaarj',
        'C\'thun',
        'the depths',
        'the shadow',
        'Ahn\'qiraj',
        'Azjol Nerub',
        'the imprisoned one',
        'the nameless elder',
        'the old one',
        'the faceless ones',
        'manifold eyes',
        'maddening whispers',
        'the maddening gaze',
        'a thousand truths',
        'unspeakable horror',
        'the god of death',
        'the god of the deep',
        'the formless one',
        'eternal servitude',
        'the black empire',
        'the all-seeing eye',
        'the drowned'
      ]
    }
  ];

  rarities = [
    {
      name: 'legendary',
      chance: .1,
      color: 'fix',
      level: 5,
      value: 60
    },
    {
      name: 'epic',
      chance: .25,
      color: 'diff',
      level: 4,
      value: 30
    },
    {
      name: 'rare',
      chance: .45,
      color: 'md',
      level: 3,
      value: 20
    },
    {
      name: 'uncommon',
      chance: .75,
      color: 'CSS',
      level: 2,
      value: 10
    },
    {
      name: 'common',
      chance: 1,
      color: '',
      level: 1,
      value: 0
    }
  ];

	constructor() {
		super();
	}

  run(message) {
    const random = Math.random();
    let rarity = this.rarities.find(({ chance }) => chance > random) || getRandom(this.rarities);
    const data = getRandom(this.data);
    const loot = this.getItemName(data, rarity);
    const goldValue = this.getGoldValue(loot, rarity);
    const gold = this.getGoldValueMessage(goldValue);
    const text = `You receive ${rarity.name} loot: **[${loot}]**.
    
${gold}`;
    this.post(text, message);
  }
  
  getItemName(data, rarity) {
    let name = '${type}';
    if (rarity.level >= 4) name = '${prefix}${suffix}, ${type} of ${source}';
    else if (rarity.level === 3) name = '${prefix}${suffix}';
    else if (rarity.level === 2) name = '${type} of ${source}';
    name = madlibs(name, data);
    return name.charAt(0).toUpperCase() + name.slice(1);
  }

  getGoldValueMessage(value = 0) {
    if (value > 150) return `Jackpot! You sold this item on the auction house for ${value}g.`;
    else if (value > 80) return `Score! You found a buyer for this item in trade chat who paid you ${value}g.`;
    else if (value < 10) return `Oops. You listed this item on the auction house but forgot a couple zeroes. Your item only sold for ${value}g.`;
    else return `You vendored this item for ${value}g.`;
  }
  
  getGoldValue(name = '', rarity) {
    const random = Math.random();
    if (random > .9 && rarity.level > 1) return this.formatGoldValue(getRandomNumberBetween(100, 200) + rarity.value);
    else if (random > .85) return this.formatGoldValue(getRandomNumberBetween(50, 100) + rarity.value);
    else if (random < .1 && rarity.level > 1) return this.formatGoldValue(getRandomNumberBetween(1, 5));
    else {
      let value = name.split('').map(char => char.charCodeAt(0)).reduce((acc, curr) => acc + curr);
      value = (value % 25) + 10 + rarity.value;
      return this.formatGoldValue(value);
    };
  }
  
  formatGoldValue(value = 0) {
    return Math.ceil(value);
  }
  
}
